# Copyright (C) 2015 The Dokdo Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/zerofltexx/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/seiren_fw_dram.bin:system/vendor/firmware/seiren_fw_dram.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/seiren_fw_sram.bin:system/vendor/firmware/seiren_fw_sram.bin \
    vendor/samsung/zerofltexx/proprietary/lib/hw/audio.primary.universal7420.so:system/lib/hw/audio.primary.universal7420.so \
    vendor/samsung/zerofltexx/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
    vendor/samsung/zerofltexx/proprietary/lib/libcontrolcsc.so:system/lib/libcontrolcsc.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libcontrolcsc.so:system/lib64/libcontrolcsc.so \
    vendor/samsung/zerofltexx/proprietary/lib/lib_DNSe_EP_ver216b.so:system/lib/lib_DNSe_EP_ver216b.so \
    vendor/samsung/zerofltexx/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/zerofltexx/proprietary/lib/libsamsungearcare.so:system/lib/libsamsungearcare.so \
    vendor/samsung/zerofltexx/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/zerofltexx/proprietary/lib/libsamsungRecord_ns.so:system/lib/libsamsungRecord_ns.so \
    vendor/samsung/zerofltexx/proprietary/lib/libsamsungSoundbooster_ext.so:system/lib/libsamsungSoundbooster_ext.so \
    vendor/samsung/zerofltexx/proprietary/lib/libsamsungSoundbooster_pgb.so:system/lib/libsamsungSoundbooster_pgb.so \
    vendor/samsung/zerofltexx/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libtinyalsa.so:system/lib64/libtinyalsa.so \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/bcm4358A0_V0009.0033.hcd:system/vendor/firmware/bcm4358A0_V0009.0033.hcd \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/bcm4358A1_V0041.0075.hcd:system/vendor/firmware/bcm4358A1_V0041.0075.hcd \
    vendor/samsung/zerofltexx/proprietary/lib/libexynoscamera3.so:system/lib/libexynoscamera3.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libexynoscamera3.so:system/lib64/libexynoscamera3.so \
    vendor/samsung/zerofltexx/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libexynoscamera.so:system/lib64/libexynoscamera.so \
    vendor/samsung/zerofltexx/proprietary/lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libexynosv4l2.so:system/lib64/libexynosv4l2.so \
    vendor/samsung/zerofltexx/proprietary/lib/libsensorlistener.so:system/lib/libsensorlistener.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libsensorlistener.so:system/lib64/libsensorlistener.so \
    vendor/samsung/zerofltexx/proprietary/lib/libuniplugin.so:system/lib/libuniplugin.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libuniplugin.so:system/lib64/libuniplugin.so \
    vendor/samsung/zerofltexx/proprietary/lib/hw/consumerir.exynos5.so:system/lib/hw/consumerir.exynos5.so \
    vendor/samsung/zerofltexx/proprietary/lib64/hw/consumerir.exynos5.so:system/lib64/hw/consumerir.exynos5.so \
    vendor/samsung/zerofltexx/proprietary/lib/libexynosgscaler.so:system/lib/libexynosgscaler.so \
    vendor/samsung/zerofltexx/proprietary/lib/libexynosscaler.so:system/lib/libexynosscaler.so \
    vendor/samsung/zerofltexx/proprietary/lib/libexynosutils.so:system/lib/libexynosutils.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libexynosgscaler.so:system/lib64/libexynosgscaler.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libexynosscaler.so:system/lib64/libexynosscaler.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libexynosutils.so:system/lib64/libexynosutils.so \
    vendor/samsung/zerofltexx/proprietary/vendor/lib/liblvverx_3.27.02.so:system/vendor/lib/liblvverx_3.27.02.so \
    vendor/samsung/zerofltexx/proprietary/vendor/lib/liblvvetx_3.27.02.so:system/vendor/lib/liblvvetx_3.27.02.so \
    vendor/samsung/zerofltexx/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/zerofltexx/proprietary/vendor/lib64/egl/libGLES_mali.so:system/vendor/lib64/egl/libGLES_mali.so \
    vendor/samsung/zerofltexx/proprietary/bin/gps.cer:system/bin/gps.cer \
    vendor/samsung/zerofltexx/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/zerofltexx/proprietary/lib64/hw/gps.default.so:system/lib64/hw/gps.default.so \
    vendor/samsung/zerofltexx/proprietary/lib/libwrappergps.so:system/lib/libwrappergps.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libwrappergps.so:system/lib64/libwrappergps.so \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/fimc_is_fw2_imx240.bin:system/vendor/firmware/fimc_is_fw2_imx240.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/setfile_4e6.bin:system/vendor/firmware/setfile_4e6.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/setfile_imx240.bin:system/vendor/firmware/setfile_imx240.bin \
    vendor/samsung/zerofltexx/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libion.so:system/lib64/libion.so \
    vendor/samsung/zerofltexx/proprietary/lib/libion_exynos.so:system/lib/libion_exynos.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libion_exynos.so:system/lib64/libion_exynos.so \
    vendor/samsung/zerofltexx/proprietary/app/FFFFFFFF000000000000000000000001.drbin:system/app/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:system/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:system/app/mcRegistry/07060000000000000000000000000000.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff00000000000000000000000b.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000b.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff00000000000000000000000e.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000e.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff000000000000000000000014.tlbin:system/app/mcRegistry/ffffffff000000000000000000000014.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff000000000000000000000016.tlbin:system/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff000000000000000000000017.tlbin:system/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff000000000000000000000018.tlbin:system/app/mcRegistry/ffffffff000000000000000000000018.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff000000000000000000000019.tlbin:system/app/mcRegistry/ffffffff000000000000000000000019.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff00000000000000000000001f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000001f.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffff000000000000000000000021.tlbin:system/app/mcRegistry/ffffffff000000000000000000000021.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffffd00000000000000000000014.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000014.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/ffffffffd00000000000000000000017.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000017.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/fffffffff0000000000000000000001b.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001b.tlbin \
    vendor/samsung/zerofltexx/proprietary/app/mcRegistry/fffffffff0000000000000000000001e.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001e.tlbin \
    vendor/samsung/zerofltexx/proprietary/bin/cs:system/bin/cs \
    vendor/samsung/zerofltexx/proprietary/lib/hw/nfc_nci.universal7420.so:system/lib/hw/nfc_nci.universal7420.so \
    vendor/samsung/zerofltexx/proprietary/lib64/hw/nfc_nci.universal7420.so:system/lib64/hw/nfc_nci.universal7420.so \
    vendor/samsung/zerofltexx/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/zerofltexx/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libreference-ril.so:system/lib64/libreference-ril.so \
    vendor/samsung/zerofltexx/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libril.so:system/lib64/libril.so \
    vendor/samsung/zerofltexx/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libsecnativefeature.so:system/lib64/libsecnativefeature.so \
    vendor/samsung/zerofltexx/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libsecril-client.so:system/lib64/libsecril-client.so \
    vendor/samsung/zerofltexx/proprietary/lib/hw/sensors.universal7420.so:system/lib/hw/sensors.universal7420.so \
    vendor/samsung/zerofltexx/proprietary/lib64/hw/sensors.universal7420.so:system/lib64/hw/sensors.universal7420.so \
    vendor/samsung/zerofltexx/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/samsung/zerofltexx/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/samsung/zerofltexx/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/samsung/zerofltexx/proprietary/lib/libMcClient.so:system/lib/libMcClient.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libMcClient.so:system/lib64/libMcClient.so \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/bcmdhd_apsta.bin_a1:system/etc/wifi/bcmdhd_apsta.bin_a1 \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/bcmdhd_ibss.bin:system/etc/wifi/bcmdhd_ibss.bin \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/bcmdhd_ibss.bin_a1:system/etc/wifi/bcmdhd_ibss.bin_a1 \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/bcmdhd_mfg.bin_a1:system/etc/wifi/bcmdhd_mfg.bin_a1 \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/bcmdhd_sta.bin_a1:system/etc/wifi/bcmdhd_sta.bin_a1 \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/cred.conf:system/etc/wifi/cred.conf \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_mfg.txt_a1:system/etc/wifi/nvram_mfg.txt_a1 \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_mfg.txt_b85_a1:system/etc/wifi/nvram_mfg.txt_b85_a1 \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_mfg.txt_murata:system/etc/wifi/nvram_mfg.txt_murata \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_mfg.txt_murata_a1:system/etc/wifi/nvram_mfg.txt_murata_a1 \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_mfg.txt_murata_b85_a1:system/etc/wifi/nvram_mfg.txt_murata_b85_a1 \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_mfg.txt_wisol:system/etc/wifi/nvram_mfg.txt_wisol \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_mfg.txt_wisol_a1:system/etc/wifi/nvram_mfg.txt_wisol_a1 \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_mfg.txt_wisol_b85_a1:system/etc/wifi/nvram_mfg.txt_wisol_b85_a1 \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_net.txt_a1:system/etc/wifi/nvram_net.txt_a1 \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_net.txt_b85_a1:system/etc/wifi/nvram_net.txt_b85_a1 \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_net.txt_murata:system/etc/wifi/nvram_net.txt_murata \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_net.txt_murata_a1:system/etc/wifi/nvram_net.txt_murata_a1 \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_net.txt_murata_b85_a1:system/etc/wifi/nvram_net.txt_murata_b85_a1 \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_net.txt_wisol:system/etc/wifi/nvram_net.txt_wisol \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_net.txt_wisol_a1:system/etc/wifi/nvram_net.txt_wisol_a1 \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/nvram_net.txt_wisol_b85_a1:system/etc/wifi/nvram_net.txt_wisol_b85_a1 \
    vendor/samsung/zerofltexx/proprietary/etc/wifi/olsrd.conf:system/etc/wifi/olsrd.conf
